language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1

after_success:
- julia -e 'using Pkg; cd(Pkg.dir("AdjPlateCap")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
